### ISSUE TITLE
External mounted HDD is not displayed in devices list under Disk usage category

### ISSUE THREAD

**Issue by ghost** [PierreKieffer/pitop#1]
Hi! Not sure if this feature isn't implemented yet or it's a bug, external mounted HDD devices are not listed under Disk usage category.

Topology: Quad Core model: ARMv7 v7l variant: cortex-a53 bits: 32 type: MCP 
Speed: 1400 MHz min/max: 600/1400 MHz Core speeds (MHz): 1: 1400 2: 1400 3: 1400 4: 1400

![image](https://user-images.githubusercontent.com/7439815/105340645-6f1d7180-5bde-11eb-88d0-3418a35564b5.png)

**Comment by PierreKieffer** [comment]
Hi @clrOne , thank you for the feedback, 
no it's not implemented, but i like this idea and it is usefull, 
I'll work on it as soon as possible !

**Comment by PierreKieffer** [comment]
Hi @clrOne , 
I implemented and merged the feature, 
You can try it by updating your version, You just need to re run the same install cmd you used for your pi 
Give me some feedbacks, and you can close the issue if it's ok with the implementation

**Comment by ghost** [comment]
Hi @PierreKieffer ! Thanks for the update, the mounted devices are now visible ✓

![image](https://user-images.githubusercontent.com/7439815/105516962-bedf6400-5cd6-11eb-8935-60a8645f0bea.png)
